javafx:
  stage:
    resizable: true
  title: 高校档案管理
  appicons: /photos/splashScreen.jpg
spring:
  #  activemq:
  #    #        broker-url: tcp://192.168.1.123:61616
  #    #        broker-url: tcp://192.168.2.66:61616
  #    broker-url: tcp://localhost:61616
  #    user: admin
  #    password: admin
  #  profiles:
  #    active: prod
  #  activiti:
  #    check-process-definitions: false
  #
  #
  #  redis:
  #
  #    host: 192.168.40.201
  #    port: 6379
  #    password: ''
  #    # 连接超时时间 单位 ms（毫秒）
  #    timeout: 3000
  #=========redis线程池设置=========
  #    pool:
  #      # 如果赋值为-1，则表示不限制；pool已经分配了maxActive个jedis实例，则此时pool的状态为exhausted(耗尽)。
  #      max-active: 10
  #      #连接池中的最小空闲连接，默认值也是0。
  #      min-idle: 0
  #      # 连接池中的最大空闲连接，默认值也是8。
  #      max-idle: 10
  #      # 等待可用连接的最大时间，单位毫秒，默认值为-1，表示永不超时
  #      max-wait: 1000
  devtools:
    restart:
      enabled: true #开启热部署
      additional-paths: src/main/java #重启目录
  freemarker:
    cache: false
  datasource:
    #   数据源基本配置
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/filemanager?characterEncoding=utf-8&useUnicode=true&serverTimezone=UTC
    type: com.alibaba.druid.pool.DruidDataSource

mybatis:
  # 指定全局配置文件位置
  config-location: classpath:mybatis-config.xml
  # 指定sql映射文件位置
  mapper-locations: classpath:mappers/*.xml



server:
  port: 8087

---


server:
  port: 8085
spring:
  profiles: dev

---

server:
  port: 8086
spring:
  profiles: prod
